fix: append cap readme
SAP-samples/fiori-tools-samples pull request #19
Opened 2022-12-09 14:40 UTC by longieirl

Append root README for CAP projects.
- some minor updates to existing README's

2022-12-09 16:59 UTC, theStiggySpd requested changes
Change in support options requested

2022-12-09 16:59 UTC, theStiggySpd commented on cap/README.md
> +- Option 2 : Use this option ONLY when you encounter any issues using the sample project with [SAP Developer tutorials](https://developers.sap.com/group.fiori-tools-lrop.html), please report it [here
hi @longieirl We can get rid of this support option.

2022-12-14 09:37 UTC, longieirl commented on cap/README.md
> +- Option 2 : Use this option ONLY when you encounter any issues using the sample project with [SAP Developer tutorials](https://developers.sap.com/group.fiori-tools-lrop.html), please report it [here
Done

2022-12-15 22:38 UTC, longieirl commented
@theStiggySpd ready whenever you are. Thanks.

2023-01-04 18:33 UTC, theStiggySpd approved these changes
looks good. Thanks much

2023-01-05 15:46 UTC, merged