Update README.md
SAP-samples/fiori-tools-samples pull request #23
Opened 2023-05-03 16:11 UTC by longieirl

Correct href links.

2023-05-09 11:37 UTC, longieirl commented
@theStiggySpd please review. Thanks.

2023-05-11 16:56 UTC, theStiggySpd requested changes
small change requested

2023-05-11 16:56 UTC, theStiggySpd commented on cap/README.md
> +2. [Standalone Approuter](../cap/cap-fiori-mta-standalone/README.md) with an inmemory database
inmemory `->` in-memory

2023-06-01 16:58 UTC, theStiggySpd approved these changes
changes looks good now

2023-06-01 16:58 UTC, merged