feat: Add third party sample project
SAP-samples/fiori-tools-samples pull request #36
Opened 2023-12-14 15:56 UTC by longieirl

- Append a new sample project showing the introduction of a third party module i.e. xml-js

2023-12-15 10:46 UTC, docirl approved these changes

2023-12-15 14:16 UTC, longieirl commented
@ashleytung can you please review, thanks.

2024-01-05 00:07 UTC, ashleytung requested changes
Hi John, i reviewed the read me files and added a a few comments on branding names.

2024-01-05 00:07 UTC, ashleytung commented on thirdpartylibrary/README.md
> +A [Fiori tools Freestyle UI application](./ztravelapp/README.md) with an external library `xml-js` enabled.
freestyle app should be referred to as `freestyle SAPUI5` app. Also, I suggest to make the sentence a bit more descriptive. Example: "[This freestyle SAPUI5 application](./ztravelapp/README.md) demonstrates how to add an external library `xml-js` to the project"

2024-01-05 00:07 UTC, ashleytung commented on thirdpartylibrary/ztravelapp/README.md
> +# Adding External Library to your Fiori UI application
SAP Fiori instead of Fiori

2024-01-05 00:07 UTC, ashleytung commented on thirdpartylibrary/ztravelapp/README.md
> +# Generate a Fiori UI Freestyle Application
"freestyle SAPUI5 application"

2024-01-05 09:26 UTC, longieirl commented on thirdpartylibrary/README.md
> +A [Fiori tools Freestyle UI application](./ztravelapp/README.md) with an external library `xml-js` enabled.
Done

2024-01-05 09:26 UTC, longieirl commented on thirdpartylibrary/ztravelapp/README.md
> +# Adding External Library to your Fiori UI application
Done

2024-01-05 09:26 UTC, longieirl commented on thirdpartylibrary/ztravelapp/README.md
> +# Generate a Fiori UI Freestyle Application
Done

2024-01-05 14:54 UTC, ashleytung approved these changes
looks good. Thank you.

2024-01-05 15:28 UTC, longieirl commented
> looks good. Thank you.

Can you please merge as I dont have access? Thanks.

2024-01-11 12:00 UTC, merged